# This is a build workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${secrets.VITE_SUPABASE_URL}
      VITE_SUPABASE_KEY: ${secrets.VITE_SUPABASE_KEY}
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Node.js version 20.10.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      # Package install
      - name: Package install
        run: npm install

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo building...

      # Runs a build
      - name: Run a build
        run: npm run build